"""sync_schema

Revision ID: f13661652605
Revises: 248ef9dd8b1b
Create Date: 2026-06-23 10:45:27.274414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13661652605'
down_revision: Union[str, Sequence[str], None] = '248ef9dd8b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_materials', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'"))
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.create_index(batch_op.f('ix_chapter_materials_chapter_id'), ['chapter_id'], unique=False)

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_chat_message_id'), ['chat_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_course_id'), ['course_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['chat_message_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('clos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clos_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('material_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_revisions_chapter_id'), ['chapter_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'"))
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.create_index(batch_op.f('ix_questions_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_chat_message_id'), ['chat_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_clo_id'), ['clo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_course_id'), ['course_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['chat_message_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_documents_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_rules_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('system_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_rules_course_id'))

    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_course_id'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_chapter_id'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['chat_message_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_questions_course_id'))
        batch_op.drop_index(batch_op.f('ix_questions_clo_id'))
        batch_op.drop_index(batch_op.f('ix_questions_chat_message_id'))
        batch_op.drop_index(batch_op.f('ix_questions_chapter_id'))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'"))

    with op.batch_alter_table('material_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_revisions_chapter_id'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))

    with op.batch_alter_table('clos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clos_course_id'))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_course_id'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_parent_id'))

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['chat_message_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_chapters_course_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_chat_message_id'))

    with op.batch_alter_table('chapter_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_materials_chapter_id'))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'"))

    # ### end Alembic commands ###
